- resources/test/main_test.go
Instead of relying on relative paths, get the path that the test is
being run from (which will be the location of the _test.go file) and use
portable path joining.
This fixes an issue I ran into when running variants of "go test ./..."
> Make integration tests more resilient to run location

- blockchain/blockchain.go
- blockchain/tasks.go
Otherwise the DB, client, etc aren't initialized.
> Disable blockchain event loop when configured as "off"

- blockchain/blockchain.go
- blockchain/tasks.go
- db/db.go
- snetd/cmd/serve.go
Prior to this commit, if you didn't specify your bolt DB configuration
via environment variables, bolt DB wouldn't be initialized properly
because that was happening in the db package's `init()` func.
Now, initialize when necessary, and remove the shared `database` global.
> Fix bolt DB initialization from command line

- resources/linuxbuild/Dockerfile
- scripts/build
> Update build script

- README.md
- config/config.go
- logger/README.md
Final PR for issue https://github.com/singnet/snet-daemon/issues/27
Adding documentation to explain snet-daemon logger configuration.
> Add snet daemon configuration documentation

- etcddb/etcddb_client.go
- etcddb/etcddb_test.go
> Etcd logging

- snetd/cmd/claim.go
- snetd/cmd/components.go
- snetd/cmd/serve.go
Refactoring to initialize components only when they are used.
> Implement lazy dependency injection

- config/config.go
- escrow/escrow.go
- escrow/escrow_test.go
- snetd/cmd/components.go
Work on https://github.com/singnet/snet-daemon/issues/72: adding expiration threshold for payment channel
> Expiration threshold

- blockchain/escrow.go
- blockchain/tasks.go
See issue https://github.com/singnet/snet-daemon/issues/106
This is temporary fix.
> Temporary fix for irrelevant blockchain error returned.

- blockchain/escrow.go
- logger/hook_test.go
Two fixes:
- skip logger mail hook unit test as it is network dependent
- use WithFields to log instead of formatting
> Various fixes

- config/config.go
- etcddb/etcddb_conf.go
- etcddb/etcddb_conf_test.go
* add "log_level" field to etcd server config
* Implement capnslog to logrus formatter
* pass etcd logs to logrus
> Pass etcd logs to logrus

- escrow/atomic_storage.go
- escrow/escrow.go
- escrow/escrow_test.go
- escrow/memory_storage.go
- escrow/payment_channel_api.go
- escrow/payment_channel_storage.go
- escrow/payment_channel_storage_test.go
- escrow/state_service_test.go
- escrow/validation_test.go
- etcddb/etcddb_client.go
- etcddb/etcddb_test.go
- snetd/cmd/claim.go
- snetd/cmd/flags.go
- snetd/cmd/list_channels.go
- snetd/main.go
Fix for issue https://github.com/singnet/snet-daemon/issues/113
New command ```snetd list channels``` is added. This command gets all of the channels from PaymentChannelService and prints them in console.
> Add command to list channels

- etcddb/README.md
Update etcd documentation according to the recent changes
* describe *payment_channel_storage_type* field
* add new etcd server properties *startup_timeout*, *log_level* and *data_dir*
* remove comments that by default the etcd server is disabled
> Update etcd documentation

- README.md
- snetd/cmd/claim.go
- snetd/cmd/list_channels.go
- snetd/cmd/list_claims.go
Add documentation for command line interface. Part of the issue https://github.com/singnet/snet-daemon/issues/72
> Add command line documentation.

- config/config.go
- handler/grpc.go
- snetd/cmd/flags.go
Remove outdated part of default configuration.
> Remove outdated configuration keys and values.

- .circleci/config.yml
- Gopkg.lock
- Gopkg.toml
- scripts/install
Fix CircleCI config to fix CI build results.
Build failure: https://circleci.com/gh/singnet/snet-daemon/170?utm_campaign=chatroom-integration&utm_medium=referral&utm_source=slack
> Fix tools versions in circleci config

- Gopkg.lock
- README.md
- blockchain/blockchain.go
- blockchain/ethereumClient.go
- blockchain/serviceMetadata.go
- blockchain/serviceMetadata_test.go
- blockchain/utils.go
- blockchain/utils_test.go
- config/config.go
- escrow/escrow_test.go
- escrow/income.go
- escrow/income_test.go
- escrow/payment_channel_storage.go
- escrow/payment_channel_storage_test.go
- escrow/validation.go
- handler/grpc.go
- ipfsutils/ipfsutils.go
- service_metadata.json
- snetd/cmd/components.go
- snetd/cmd/flags.go
- snetd/cmd/serve.go
- snetd/cmd/serve_test.go
> Service Meta Data as a component , issue #139 and also merged pull request 149

- snetd/cmd/serve.go
Fix for https://github.com/singnet/snet-daemon/issues/158
> Return port parsing error correctly, issue #158

- escrow/escrow.go
Fix for issue https://github.com/singnet/snet-daemon/issues/146
> Return internal code due to internal error

- escrow/control_service.proto
First draft for control_service.proto
> add control_service.proto

- resources/blockchain/package.json
Point to the latest version of the contract 0.2.6
> Point to the latest version of the contract 0.2.6

- escrow/escrow.go
- escrow/state_service.go
- escrow/state_service_test.go
also include the actual error that occurred to help understand the reason causing the error better 
#200
> issue #200, Return the actual error occurred 

- README.md
- config/version.go
- config/version_test.go
- scripts/build
- snetd/cmd/flags.go
- snetd/cmd/version_details.go
using ldflags , latest tagged version , sha1 revision and the buld time are set at the compile time , 
these versioning details can  now easily  be sent back on the response from Daemon
> Determine the current version of Daemon through cli commands

- .circleci/config.yml
- README.md
- scripts/build
- scripts/build-xgo
using ldflags , latest tagged version , sha1 revision and the buld time are set at the compile time ,
these versioning details can now easily be sent back on the response from Daemon
> set the daemon build version details using ldflags 

- metrics/heartbeat.go
Changed the logging type from info to debug
Issue #235
> Issue #235  : Changed the logging type from info to debug

- snetd/cmd/serve.go
https://github.com/singnet/snet-daemon/issues/209
replace stop with the recommended GracefulStop().
@vsbogd , I believe there will be more changes to fix 209 , but at least on the ones that we are clear on raising PR with small commits for your review and make progress
> Issue : 209 ( gracefullly Shutdown Daemon) 

- blockchain/serviceMetadata.go
- escrow/state_service.go
Remove the dependency with Service MetaData when the Daemon Starts when block chain is disabled
Also make sure the State Service calls dont make block chain calls when the block chain flag is disabled.
> Issue : 258 - Remove dependency with service metadata file when block chain is disabled

- README.md
- metrics/request_stats.go
- metrics/request_stats_test.go
- metrics/response_stats.go
- metrics/response_stats_test.go
will store version as a part of req/resp stats data.
> will store version as a part of req/resp stats data

- README.md
- scripts/test
> test coverage badge

- README.md
test circleci and coverall trigger
> test circleci and coverall trigger

- README.md
- scripts/test
reverting back coverall coverage display code. We will test this out separately.
> reverting back coverall coverage display code

- escrow/state_service.go
Fix authentication in GetChannelState in order to work with https://github.com/singnet/snet-cli/pull/241
> fix authentication in GetChannelState

- escrow/state_service.go
#288 
Valid Signature is now the first check before proceeding further
> #288 fix the failed test case

- scripts/build-xgo
corrected the typo in the script
> #280, be consistent with other build script of Daemon 

- config/configuration_service.proto
Refer #29  on details discussion 
#283
> Proto for Operator UI 

- README.md
> addition of test coverage badge in README file.

- .circleci/config.yml
Issues seems to be resolved with higer version of go 
#205
> Issue #205

- README.md
- authutils/auth_service_test.go
- config/blockchain_network_config_test.go
- config/config.go
- escrow/escrow_test.go
- escrow/lock.go
- escrow/payment_channel_storage.go
- escrow/payment_channel_storage_test.go
- snetd/cmd/components.go
#188 Add the network name as part of the storage key prefix
With the single channel per Organization per group , the existing key should suffice ( we dont need to
> add the network name as well on the storage key prefix 

- blockchain/orginzationMetadata.go
- blockchain/serviceMetadata.go
- blockchain/utils.go
- blockchain/utils_test.go
- config/config.go
- escrow/free_call_payment_handler.go
- escrow/payment_channel_api.go
- escrow/validation.go
- escrow/validation_test.go
- handler/interceptors.go
- resources/blockchain/package.json
- snetd/cmd/components.go
New PaymentHandler and Payments have been defined
Based on the  payment type validations kick in
> Allow  Free Call Support in Daemon

- authutils/auth_service.go
- authutils/auth_service_test.go
- config/config.go
- escrow/free_call_payment_handler.go
- metrics/Notifications.go
- metrics/request_stats.go
- metrics/response_stats.go
- metrics/utils.go
- metrics/utils_test.go
- resources/blockchain/package.json
Send the Daemon Signature while making metering calls for validation
> Issue :345 ( Signatature validation for metering calls) 

- authutils/auth_service.go
- authutils/auth_service_test.go
- escrow/free_call_payment_handler.go
- escrow/free_call_payment_handler_test.go
- metrics/Notifications.go
- metrics/request_stats.go
- metrics/response_stats.go
- metrics/utils.go
- metrics/utils_test.go
- snetd/cmd/components.go
Added Group Id as well as part of Signature for Daemon
> Issue :345

- metrics/utils.go
convert to base64 before adding it to the reuest header
> Issue 379: signature to be converted to base64

- handler/interceptors.go
- metrics/response_stats.go
- metrics/response_stats_test.go
- snetd/cmd/components.go
add the payment type in the response stats being persisted
https://github.com/singnet/snet-daemon/issues/384
> #384 : Additional details to be persisted 

- ratelimit/README.md
Added more details on ratelimiting 
https://github.com/singnet/snet-daemon/issues/389
> Better documentation in Daemon 

- config/config.go
- handler/interceptors.go
- metrics/request_stats.go
- metrics/response_stats.go
- metrics/utils.go
- ratelimit/README.md
- snetd/cmd/components.go
Validate the config file after it has been loaded for other snetd commands like 'channel'
> https://github.com/singnet/snet-daemon/issues/391

- escrow/state_service.go
- escrow/state_service.proto
Add a method to show all the channel states from Daemon , this will be used by the SDK and other clients , and Daemon will be their single point for getting channel states
#397
> Issue : 397 , Get all channel state 

- README.md
- etcddb/README.md
Updated docs to give description of newly added configurations
> Updating README Docs 

- configuration_service/configuration_service.proto
- escrow/control_service.proto
- escrow/state_service.proto
Package names to use daemon API in Java SDK.
> Add package to use services from Java SDK

- escrow/payment_channel_api.go
Add conversion for signer and groupId
> Fix payment channel print procedure

- config/config.go
- etcddb/README.md
Fix for https://github.com/singnet/snet-daemon/issues/398
I also raised PR for dev-portal: https://github.com/singnet/dev-portal/pull/95
I see that there is number of repos, which already incorporated this typo, so they need to be migrated before using new daemon version: https://github.com/search?p=1&q=org%3Asingnet+payent&type=Code
> Fix payment channel config typos

- escrow/state_service.go
- escrow/state_service_test.go
Previous version of the test mocks old variant of the ChannelStateRequest and thus doesn't test latest code.
> Mock new version of channel state request instead of old one

- escrow/free_call_payment_handler.go
- escrow/payment_handler.go
- escrow/payment_handler_test.go
- handler/interceptors.go
- handler/interceptors_test.go
- metrics/response_stats.go
Publishing latest Authorized amount on a given channel ( to show the effective balance on DAPP)
> #414- Publish latest offchain channel state ( Authorized amount) 

- escrow/free_call_payment_handler.go
- escrow/free_call_payment_handler_test.go
- escrow/payment_handler.go
#426
Use free call count from Service metadata 
Standardize go fmt formatting
> Issue #426

- config/version.go
Bug fix on the version check on Daemon and display the message when appropriate 
`There is a newer version of the Daemon %v available`
> #316 : Freecalls

- escrow/free_call_state_service_test.go
- escrow/payment_handler_test.go
Increase coverage and fix test cases 
#452
> #452 Freecalls Test case covergae 

- escrow/state_service.go
- escrow/state_service_test.go
> #447 : Give Service provider  access to the channel state

- scripts/installdaemon
Handy script to download and install daemon
#387
> #387 :Handy script to download and install daemon

- escrow/free_call.go
- escrow/free_call_api.go
- escrow/free_call_api_test.go
- escrow/free_call_test.go
> #463 :Added more detais on userdata stored for easier view 

- metrics/heartbeat.go
- snetd/cmd/components.go
Add Daemon version as well to the Daemon hearbeat
> #470 :Add Daemon version as well to the Daemon hearbeat

- config/config.go
- configuration_service/configuration_service.go
- configuration_service/configuration_service.proto
- configuration_service/configuration_service_test.go
> #472 : Autorized users for access to configuration service 

- README.md
- handler/grpc.go
We need to parametrize the max send and recv message for the passthrough endpoint point
#474
> #474 : We need to parametrize the max send and recv message for the passthrough endpoint point

- snetd/cmd/components.go
> Add Org_id and also the group_id  in the default storage path 

- escrow/control_service.go
- escrow/control_service.proto
- escrow/control_service_test.go
> #476 : Start Multiple claims from a single grpc call 

- config/config.go
- configuration_service/configuration_service.go
- configuration_service/configuration_service_test.go
hide any sensitve info from logs / response sent
> #490 :hide any sensitve info from logs / response sent

- blockchain/orginzationMetadata.go
- blockchain/orginzationMetadata_test.go
#522 
Change is backward compatible
> Get License End point from metadata 

- config/config_test.go
- handler/grpc.go
- handler/grpc_test.go
> Support Secure connections from Daemon 

- blockchain/ethereum_test_util.go
- resources/blockchain/package-lock.json
- resources/blockchain/package.json
> Point to the latest platform contract 

- config/config.go
- escrow/income.go
- training/service.go
fix inconsistent function name in comment
> chore: fix inconsistent function name in comment

- escrow/free_call_state_service.go
- escrow/payment_channel_api.go
- escrow/platumltext
- escrow/token_service.go
> chore: fix some typos

- escrow/prepaid_handler.go
- escrow/train_pay_handler.go
make function comments match function names
> chore: make function comments match function names

- metrics/README.md
- training/error.go
- training/service_test.go
fix some minor issues in comments
> chore: fix some minor issues in comments
