resources/test/main_test.go
Instead of waiting 7 seconds (for 5), wait 2 seconds (for 1).
=> Use 1-second poll time for integration test

blockchain/blockchain.go, blockchain/interceptors.go, blockchain/tasks.go, handler/handler.go, handler/http.go, resources/test/main_test.go, snetd/snetd.go
A first pass at showing how we can avoid shared global state and
implicit cross-package dependencies by threading things through. This
should greatly improve testability and maintainability in the long term.
=> Remove globals and init() side-effects from blockchain package

blockchain/blockchain.go, blockchain/tasks.go, handler/grpc.go, handler/handler.go, handler/http.go, scripts/lint, scripts/test, snetd/cmd/serve.go
=> Add information-only golint to test runs

blockchain/tasks.go, config/config.go, resources/test/main_test.go, snetd/cmd/flags.go
These are bound with cobra/viper, so you can still set them (and fetch
them) via viper (hence no code changes to config fetching). But now you
can also specify them on the command line, and `snetd --help` will show
available flags.
```
go run ./snetd/main.go --help
Usage:
snetd [flags]
Flags:
-b, --blockchain                 enable blockchain processing (default true)
-c, --config string              config file (default "snetd.config")
--db-path string             database file path (default "snetd.db")
--ethereum-endpoint string   ethereum JSON-RPC endpoint (default "http://127.0.0.1:8545")
-h, --help                       help for snetd
--mnemonic string            HD wallet mnemonic
--passthrough                passthrough mode
--poll-sleep string          blockchain poll sleep time …
```
=> Add basic command-line daemon flags

Gopkg.lock, Gopkg.toml, config/config.go, snetd/cmd/flags.go, snetd/cmd/serve.go
This change adds automatic SSL support via LetsEncrypt ("http-01"
challenge, since tls-sni- challenges were disabled recently for
security issues).
If requested, the daemon now fetches certs and serves gRPC/HTTP over TLS
when requested.
=> Add SSL/TLS and LetsEncrypt autocert support

resources/test/main_test.go
An extra sanity check, this will for example return non-zero if the
daemon fails to start up due to the listen port already being in use.
=> Check and assert daemon exit code on integration test

config/config.go, snetd/cmd/flags.go, snetd/cmd/serve.go
Now that we support TLS listening, extend SSL support from just
LetsEncrypt/autocert to also using a local pair of keyfiles.
=> Support SSL via local X509 keypair

resources/blockchain/truffle.js, resources/test/main_test.go
This way, you can have multiple test runs on the same machine, or have a
local ganache/daemon running on the standard ports for development and
still be able to run the tests.
While in here, trim redundant daemon environment variables.
=> Use dynamic TCP ports for test run

resources/test/main_test.go
Not used yet, but may lead to strange issue when we do start using it...
=> Fix environment typo in test harness

config/config.go, snetd/cmd/flags.go, snetd/cmd/init.go, snetd/cmd/serve.go, snetd/main.go
- initialize logger after loading configuration from file
- add root Cobra command and two children: ```serve``` and ```init```
- implement ```init``` to save config to file specified
- make ```snetd``` run ```serve``` by default for backward compatibility
=> Add ```snetd init``` command to save default configuration file.

resources/test/grpc.go, resources/test/grpc_web.go, resources/test/harness.go, resources/test/main_test.go, resources/test/utility.go
Fix package name and internal functions definition places to allow ```go build``` and such tools as ```gorename``` working without issues.
=> Fix resource test package

snetd/cmd/flags.go
Fix case when user doesn't specify configuration file but default configuration file ```snetd.config.json``` exists in filesystem. Before fix snet-daemon ignored this file.
=> Fix read default config if file exist

config/config.go, snetd/cmd/flags.go, snetd/cmd/init.go, snetd/cmd/serve.go
Move loading configuration and logger initialization out of cobra
initialization. The reason is not all of commands need load
configuration and initialize logger. ```snetd init``` for instance
doesn't need it.
=> Load configuration only when starting daemon.

config/config.go, logger/logger.go, logger/logger_test.go, snetd/cmd/serve.go
Work on issue https://github.com/singnet/snet-daemon/issues/27.
What is done:
- add default configuration for the snet-daemon including logger configuration
- add logger module with InitLogger function to parse the configuration and initialize logger
- add wrapper for logger formatter to format logger timestamps using configured timezone
- add file writer which supports log rotation
- add unit tests for the logger initialization subsystem
What is not done:
- documentation for the logger configuration
=> Issue #27: add logger configuration

scripts/test
Use ```go test ./...``` command to run all of unit tests not only ```resources/test```.
```
$ go test ./...
?   	github.com/singnet/snet-daemon/blockchain	[no test files]
?   	github.com/singnet/snet-daemon/codec	[no test files]
?   	github.com/singnet/snet-daemon/config	[no test files]
?   	github.com/singnet/snet-daemon/db	[no test files]
?   	github.com/singnet/snet-daemon/handler	[no test files]
?   	github.com/singnet/snet-daemon/resources/installBlockchainDependencies	[no test files]
ok  	github.com/singnet/snet-daemon/resources/test	41.306s
?   	github.com/singnet/snet-daemon/resources/test/echoservice	[no test files]
ok  	github.com/singnet/snet-daemon/snetd	0.021s
?   	github.com/singnet/snet-daemon/snetd/cmd	[no test files]
```
=> Modify ./scripts/test to run all of unit tests

config/config.go, config/config_test.go, logger/logger.go, logger/logger_test.go, snetd/cmd/serve.go
Implement SubWithDefault method to replace viper.Sub(). viper.Sub() suffers from issue https://github.com/spf13/viper/issues/559. SubWithDefault method workarounds issue by adding default values to the sub configuration returned.
Fix logger initialization code accordingly. Add unit tests for new methods and fix old unit tests.
=> More elegant solution for viper subs with defaults

.circleci/config.yml
The fix allows to trigger the platform-pipeline after the current build successful execution.
It requires that in the CircleCI dashboard:
1. A token with name  CIRCLECI_PLATFORM_PIPELINE_TOKEN is created 
Workflows -> platform-pipeline -> Settings -> API Permissions with necessary permissions.
2. The CIRCLECI_PLATFORM_PIPELINE_TOKEN env variable is added to the snet-daemon 
Workflows -> snet-daemon-> Settings ->Environment Variables
=> Trigger platform-pipeline build after successful execution

blockchain/blockchain.go, blockchain/escrow.go, blockchain/interceptors.go, blockchain/interceptors_test.go, blockchain/job.go
Start of the work on issue https://github.com/singnet/snet-daemon/issues/31
As we are introducing new way of payment MultiPartyEscrow contract (see https://github.com/singnet/platform-contracts/pull/39) we need to support it in ```snet-daemon```. In order to do this I have modified gRPC interceptor to switch between two different ways of payment:
- job - an old one
- escrow - new way using escrow contract
Proposed API is described at [multiPartyEscrowApiChanges.md#daemon-api-changes](https://github.com/singnet/wiki/blob/master/multiPartyEscrowContract/multiPartyEscrowApiChanges.md#daemon-api-changes) page
What is done:
- move Job verification code to the ```blockchain/job.go```
- move MultiPartyEscrow payment channel verification code to the ```blockchain/escrow.go```
- add factory method …
=> Add gRPC interceptor stub to check gRPC escrow contract payment channel state

config/config.go, logger/logger.go, logger/logger_test.go
Working on issue https://github.com/singnet/snet-daemon/issues/27
Add logger "timezone" parameter to configure formatter and output timezone at once. Fix unit tests accordingly. Improve previous unit tests.
=> Add single timezone parameter for logger.

escrow/escrow.go, escrow/escrow_test.go, escrow/storage.go, snetd/cmd/serve.go
Work on issue https://github.com/singnet/snet-daemon/issues/31
What is done:
- added payment channel storage which gets payment channel information from blockchain if it cannot find it in main storage
- payment channel storage API is improved to separate key absence and storage access error as suggested in https://github.com/singnet/snet-daemon/pull/59#discussion_r224355807
=> Poll new payment channels from blockchain

Gopkg.lock, Gopkg.toml, blockchain/blockchain.go, blockchain/job.go, blockchain/tasks.go, db/db.go, escrow/storage.go, etcddb/README.md, etcddb/etcddb_client.go, etcddb/etcddb_server.go, etcddb/etcddb_test.go, etcddb/payment_channel_storage.go, snetd/cmd/serve.go
This is an initial fix which includes etcd as a payment storage into snet-daemon project.
It includes two main structures 
* EtcdServer
* EtcdClient
and some basic operations on it.
The etcddb_test.go test show basic usage like using a config file to start an etcd server and read/write values to it.
The example of the config file:
```
{
"PAYMENT_CHANNEL_STORAGE_CLUSTER": "storage_1=http://127.0.0.1:2380",
"PAYMENT_CHANNEL_STORAGE": {
"ID": "storage_1",
"HOST" : "127.0.0.1",			
"CLIENT_PORT": 2379,
"PEER_PORT": 2380,
"TOKEN": "payment_channel_storage_token",
"ENABLED": true
}
}
```
=> #63 Using embedded etcd server as a payment channel storage

Gopkg.toml, snetd/cmd/serve.go
Fix to allow CORS pre-flight requests to daemon, allow CORS requests to unregistered (unknown) gRPC services
=> grpc-web: fix CORS issue with OPTIONS method in pre-flight requests from browsers

config/config.go, snetd/cmd/serve.go
Print configuration on daemon start to know which configuration values are actually used.
Change default configuration format to text because json has random sorting.
Hide sensitive values.
=> Print config to log on start.

codec/codec.go
Add fake import to guarantee that default protobuf codec is registered first.
=> Guarantee correct order of codec registering

snetd/cmd/claim.go, snetd/cmd/components.go, snetd/cmd/flags.go, snetd/cmd/serve.go
Work on issue https://github.com/singnet/snet-daemon/issues/72
What is done:
- claim command is added to daemon to claim money from the payment channel
- current implementation increments payment channel nonce but not sends transaction to the blockchain
- common components between serve.go and claim.go are moved into components.go in order to share initialization code and separate dependency injection from business logic
What's next:
- add a call of MultiPartyEscrow contract to claim the money
=> Implement payment claim

config/config.go, etcddb/etcddb_conf.go, etcddb/etcddb_server.go, etcddb/etcddb_test.go, snetd/cmd/components.go, snetd/cmd/serve.go
There are several changes:
* Read etcd client/server default values from the default config file
* Move etcd server starting to components before etcd client initialization.
* Enable etcd server running by default in the config file 
There is separate issue on running etcd client asynchronously #91
=> Enable etcd storage by default in the config file

blockchain/blockchain.go, escrow/income.go, escrow/income_test.go, snetd/cmd/components.go
Agent is not used in income validator anymore as we agreed on using configuration value.
=> Remove Agent usage from income validator.

blockchain/blockchain.go, blockchain/ethereum_test_util.go, escrow/combined_storage.go, escrow/combined_storage_test.go, escrow/escrow.go, escrow/escrow_test.go
Work on issue https://github.com/singnet/snet-daemon/issues/72
What is done:
- current ethereum block number is used instead of expiration timestamp
=> Use number of blocks to validate expiration

config/config.go, etcddb/etcddb_client.go, etcddb/etcddb_conf.go, etcddb/etcddb_conf_test.go, etcddb/etcddb_server.go, etcddb/etcddb_test.go
The fix allows to configure  etcd client/server timeouts in a config file using time units.
SubWithDefault()  is used to load Viper config with default values.
=> Define etcd server timeouts in config

config/config.go, etcddb/etcddb_conf.go, etcddb/etcddb_conf_test.go, etcddb/etcddb_server.go, etcddb/etcddb_test.go
* **data_dir** property is added to the EtcdServer configuration file
* gunit is used in tests to run setup and teardown methods
* test data dirs are cleaned
=> Clean etcd tests work directories

etcddb/etcddb_client.go, etcddb/etcddb_test.go
The current fix proposes a simple API  to use mutex-es in Etcd client
- The etcd session is created only once and is kept in etcd client
- Each mutex is created for the given key
- Context is used to cancel an etcd lock or to stop it by timeout
- Mutex-es for the same session do not block each other. Only different clients with different sessions are blocked if a mutex is used for the same key.
=> Etcd client mutex implementation

etcddb/etcddb_client.go, etcddb/etcddb_test.go
The etcd client Transaction method uses an array of key/values to call compare and swap operation.
For example:
```
ok, err := client.Transaction(
[]EtcdKeyValue{
EtcdKeyValue{key: key1, value: expect1},
EtcdKeyValue{key: key2, value: expect2},
},
[]EtcdKeyValue{
EtcdKeyValue{key: key2, value: update2},
EtcdKeyValue{key: key3, value: update3},
},
)
```
Another approach is to use maps as arguments in the Transaction method: https://github.com/stellarspot/snet-daemon/commit/aeeb5519bbf11142be24bada62ce53171cf4731d
```
expect := map[string]string{
key1: expect1,
key2: expect2,
}
swap := map[string]string{
key2: update2,
key3: update3,
}
ok, err := client.Transaction(expect, swap)
```
This does not require additional EtcdKeyValue struct but using maps itself can give additional memory …
=> Add etcd Transcation method

escrow/escrow.go, escrow/escrow_test.go, escrow/memory_storage.go, escrow/payment_channel_api.go, escrow/payment_channel_storage_test.go, escrow/payment_storage.go, snetd/cmd/claim.go, snetd/cmd/flags.go, snetd/cmd/list_channels.go, snetd/cmd/list_claims.go
Work for issue https://github.com/singnet/snet-daemon/issues/108:
- new command ```snetd list claims``` is added to list payments which were started but not written to the blockchain yet
- new flag ```--payment-id``` is added to ```snetd claim``` command for writing started payment to the blockchain
=> Add command to list payments in progress

blockchain/blockchain.go, config/config.go, snetd/cmd/claim.go
As private key is needed for ```snetd claim``` command only it should not be validated during starting of the daemon. ```snetd claim``` checks that blockchain component has configured identity instead.
=> Remove private key validation for daemon

handler/interceptors.go
- paymentHandler.CompleteAfterError() method is deferred
- panic mode after handler(...) call is handler
=> #145 Call payment.CompleteAfterError() even if panic() happens

.gitignore, escrow/escrow.go, escrow/income.go, escrow/income_test.go, escrow/payment_channel_api.go, escrow/payment_handler.go, escrow/payment_handler_test.go, escrow/validation.go, escrow/validation_test.go, handler/grpc_test.go, handler/grpc_test.proto, handler/interceptors.go, handler/interceptors_test.go
Depends on https://github.com/singnet/snet-daemon/pull/162
Fix for issue https://github.com/singnet/snet-daemon/issues/163
What is done:
- new GrpcError type is added to make possible returning more structured information about error from PaymentHandler interface
- custom gRPC error code IncorrectNonce is added to return incorrect nonce error to client
- unit test is added to check that gRPC allows returning custom errors
=> Return incorrect nonce error

blockchain/escrow.go, escrow/escrow.go, escrow/escrow_test.go, escrow/payment_channel_api.go, escrow/payment_channel_storage.go, escrow/payment_channel_storage_test.go, escrow/state_service.go, escrow/state_service_test.go, escrow/validation.go, escrow/validation_test.go
Fix for https://github.com/singnet/snet-daemon/issues/144
Channel sender signature check is replaced by channel signer signature check in payment validation and channel state request authorization.
=> Use signer to check signature

README.md, config/config.go, logger/README.md
Update snet-daemon configuration documentation to fix https://github.com/singnet/snet-daemon/issues/151
and unblock https://github.com/singnet/wiki/issues/32.
what is done:
- documentation updated
- property names are converted to the same case (lowcase)
- defaults for ```private_key```  and ```auto_ssl_cache_dir``` properties are added
- legacy ```daemon_listening_port``` property is removed
=> Update daemon configuration documentation

Gopkg.toml, ipfsutils/ipfsutils.go
@astroseger @vsbogd @raamb @anandrgit 
this fix involves generating the IPFS multihash from the IPFS provided metadata and validate against the requested IPFS metadata using Hash. Both generated and requested hashes must match to consider the metadata is valid and secure.
Can you review the fix and provide your comments
=> check hash of files from IPFS (fix for issue #176)

Gopkg.toml, README.md, config/config.go, ipfsutils/ipfsutils.go
@vsbogd @raamb @anandrgit 
By default, IPFS reads/writes has time out for more than a minute. If there is no file found in IPFS, then the shell keeps waiting for the file until timeout occurs, during which daemon looks hanged. 
A configurable timeout has been added (defaulted to 30 sec) to Daemon to control the timeout duration to reduce effects of empty IPFS or non existence of files in IPFS. if in case of a real empty IPFS file  returned, then unmarshalling to metadata fails and eventually daemon will not run anymore.
Please review and let us know you comments/suggestions.
=> fix for issue when Daemon hangs if no service metadata in IPFS (issue #170)

escrow/payment_handler.go
Once you hit the error "income % does not equal to price % ", the channel will get locked
Ensure that Rollback() is done in such a scenario
Also related to singnet#172
=> Channel gets locked when you see "income % does not equal to price % ", error Issue #172

escrow/state_service.proto, handler/interceptors.go, handler/interceptors_test.go
This is to close issue https://github.com/singnet/snet-daemon/issues/145
Convert unit tests to test suite. Add unit tests for error handling. Fix panic type conversion issue.
Better review by commits, last two are most significant:
- https://github.com/singnet/snet-daemon/pull/194/commits/2b330f3b3fd61d394ed864ba56c3869fc67a54b8
- https://github.com/singnet/snet-daemon/pull/194/commits/17eec17f08ae66b404d3c65da09bbe12f29555e0
=> Channel lock cleanup test

metrics/clients.go, metrics/heartbeat_test.go, metrics/register.go, metrics/register_test.go, metrics/request_stats.go, metrics/request_stats_test.go, metrics/response_stats.go, metrics/response_stats_test.go, metrics/utils.go, metrics/utils_test.go, snetd/cmd/components.go, snetd/cmd/serve.go
Registering Daemon will send back a valid token , this token will be used to publish the monitoring payload ( request and response stats ).
Network details are added as part of payload to identify the which network and the contract being used by the application publishing these stats.
=> Daemon Monitoring - Token Registration and Validation

README.md, blockchain/serviceMetadata.go, blockchain/serviceMetadata_test.go, config/config.go, metrics/heartbeat_test.go, metrics/register.go, metrics/register_test.go, metrics/request_stats_test.go, metrics/response_stats.go, snetd/cmd/serve.go, snetd/cmd/serve_test.go
Issue #199 
Get away from the Daemon End Point
Introduce group name to help with payments
Define the port number that the Daemon should listen to .
The issue with having a daemon end point was that it was forcing the endpoint defined to be exactly the same as what has been defined in the metadata ( this may not always be true as the daemon could run in a private network behind the NAT)
What has been defined in the meta data is for public access, how daemon runs in its private network or container should be agnostic to this public end point
=> Issue #199  Behind NAT support 

blockchain/serviceMetadata.go
If the Given OrganizationID and Service ID are not found in block chain, return back the error quoting this reason
#206
=> #issue 206, Better error handling 

config/config.go, logger/README.md, logger/logger.go, logger/logger_test.go
Add new field timestamp_format into logger configuration to allow showing nanoseconds in timestamps.
Add nanoseconds by default.
=> Add nanoseconds to the timestamp

escrow/escrow.go, handler/interceptors.go, handler/interceptors_test.go
Move Complete() call to the deferred block to have all payment completion logic in same place.
Add logs to payment handler to clearly designate payment completion state and channel state in logs.
Add unit test to test Complete() call.
=> Simplify gRPC interceptor logic

README.md, ratelimit/rateLimit.go, scripts/build-xgo, scripts/watcher_fsevents_cgo.go.patch, snetd/cmd/serve.go
I've added a script using xgo, to allow us to build for arm6 (raspberry pi). Fixes #227
Side benefit of this is approach is that I was able to build for almost every platform Go supports (so also fixes #215).
However, I've constrained the default behaviour to only build for the major platforms.
Also changes some Int64 constants to fit in Int32 so compilation on arm works.
=> Support cross compilation with xgo

config/config.go, config/config_test.go
Mainly to check they are not the same and fix #217
Doesn't catch any ipv6 stuff, or whether a domain resolves to the same IP, but should catch the bad config I was using that had the daemon calling itself, and that confused me for a couple of days! :sweat_smile:
=> Add config check to validate daemon and passthrough endpoints

README.md, config/config.go, snetd/cmd/serve.go
Default value has been set to 4MB 
Any attempt to set the value  beyond 4GB will fail with an error
=> Issue : 195 -  make the max message size a config key.

snetd/cmd/serve.go
changes made inside a method with a pointer receiver is visible to the caller whereas this is not the case in value receiver
made start to have pointer receiver
=> https://github.com/singnet/snet-daemon/issues/209

escrow/state_service.go, escrow/state_service_test.go, snetd/cmd/components.go
add mpe_address to the message in GetChannelState authentication.
So the client should sign the following message: __get_channel_state , **mpe_address**, Channel ID, Current block
=> #287, Add mpe_address to GetChannelState authentication

config/config.go, metrics/README.md, metrics/clients_test.go, metrics/heartbeat_test.go, metrics/register_test.go
corrected the Obsolete mockable URL used in Daemon metrics
Removed the usage of default service heartbeat as a mockable url
#340
=> Issue 340: Correct the mockable url of Daemon 

.circleci/config.yml, blockchain/orginzationMetadata.go, blockchain/orginzationMetadata_test.go, blockchain/serviceMetadata.go
As part of Supporting a single channel per Organization per Group (Payment Group across the services)  we will need all the services to share the same channel state. We need to standardize what this state is across all services belonging to the same group.
Please note , more PR will follow to remove data points being used from service metadata and replace them with data from Organization metadata
=> Single Channel ( Support for reading Organization - Group Level Metadata) 

escrow/payment_handler.go, escrow/payment_handler_test.go, handler/interceptors.go, metrics/request_stats.go, metrics/request_stats_test.go, metrics/response_stats.go, metrics/response_stats_test.go
#322 
Details like thebelow will be set by the respective clients and added to the Daemon metrics 
- type of client calling Deamon ( ex Snet-cli, Dapp, SDK) , these will be set by the respective clients 
- user adderss
=> Capture additional user details in Daemon Metrics 

escrow/validation.go, escrow/validation_test.go
Changes to the Signature per the latest MPE Contract
adding a prefix __MPE_claim_message
This is not to be merged till the latest contract is deployed
=> https://github.com/singnet/snet-daemon/issues/342

escrow/validation.go, escrow/validation_test.go, ratelimit/rateLimit.go, scripts/test
per the latest contract, the sender can also be a signer
=> Isseu 374: Sender can also be a potential signer 

escrow/payment_handler.go, escrow/state_service.go, escrow/state_service_test.go
All clients using Daemon ( ex SDK, DAPP and snet-cli) have updated to use the new proto , and hence removing the obsolete code
https://github.com/singnet/snet-daemon/issues/278
=> #278, remove obsolete code on checking old signatures

blockchain/serviceMetadata.go, blockchain/serviceMetadata_test.go
service metadata now has a place holder to define the number of free calls allowed .Give placeholders to use this field
More test cases for coverage and go fmt formatting
=> Issue #426: get number of free calls allowed from the service metadata 

escrow/state_service.proto
As singnet/snet-daemon#99 is closed, I think we can remove the banner.
=> Remove warning banner

README.md, blockchain/serviceMetadata_test.go, config/config.go, metrics/response_stats.go, snetd/cmd/components.go
#439 
Previously free-calls were used for metering , now Damon maintains a record/storage of all free call, this is to clean up the obsolete code in Daemon
=> Freecalls - Remove configs for free_call

scripts/installdaemon
The default docker containers run with root as the user, so the `sudo mv ...` was crashing:
```
./installdaemon: line 9: sudo: command not found
```
=> [scripts] Using sudo only if necessary.

escrow/control_service.go, escrow/control_service.proto
pass the Channels' expiry on the response  This information is valuable for the user to determine which claims need Urgent attention and are gonna expire soon / have expired
#481
=> #481 : Add the channels Expiry as part of the response sent back 

configuration_service/configuration_service.go
#485 
Check if the Signature is not Expired only when block chain is enabled, current block number has no
meaning when block chain is in Disabled mode
=> #485 : Support grpc configuration service calls when block chain mode disabled 

README.md, config/config.go, config/config_test.go
by default enforce this behavoir
set passthrough_enabled = true
the user also needs to specify a valid URL for the config passthrough_endpoint
user has the choice to set the value to false explicitly
=> #487 :set passthrough_enabled = true by default 

escrow/memory_storage.go, escrow/prepaid_handler.go, escrow/prepaid_service.go, escrow/prepaid_service_test.go, escrow/token_service.go, escrow/token_service.proto, escrow/token_service_test.go, handler/interceptors.go, snetd/cmd/components.go, snetd/cmd/serve.go, token/jwttoken.go, token/token_service_api.go
#309 
Get a token to make concurrent calls
=> Gettoken for concurrent calls 

escrow/atomic_storage.go, escrow/free_call_storage.go, escrow/payment_channel_storage.go, escrow/payment_storage.go, escrow/prepaid_handler.go, escrow/prepaid_service.go, escrow/prepaid_service_test.go, escrow/prepaid_storage.go
=> #509 : Bug fix on key generation 

metrics/clients_test.go, metrics/heartbeat_test.go, metrics/register_test.go, training/training.proto
Fix the build and get away from mockables 
#429
=> #426 - get away from mockables

config/config.go
The intention here should be to initialize a slice with a capacity of `len(users)` rather than initializing the length of this slice.
The online demo: https://go.dev/play/p/q1BcVCmvidW
=> fix: fix slice init length

metrics/README.md, storage/atomic_storage.go
improved wording and consistency in code:
`resposne` - `response`
`implementor` - `implementer`
=> minor text cleanup
